# Generated by Django 5.1.4 on 2025-02-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('lunch', 'Almoço'), ('dinner', 'Janta')], max_length=6),
        ),
    ]
