# Generated by Django 5.1.4 on 2025-02-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_meal_image_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(upload_to='meals_images/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('lunch', 'Almoço'), ('dinner', 'Janta')], max_length=6),
        ),
    ]
