# Generated by Django 4.2.6 on 2025-03-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='day',
            field=models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira')], default=None, max_length=20),
        ),
    ]
