# Generated by Django 4.2.6 on 2025-03-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_meal_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='day',
        ),
    ]
